version: '3.8'

services:
  # 后端服务
  chat-sse-be:
    build: .
    container_name: chat-sse-be
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - SERVER_PORT=8121
      - DEEPSEEK_API_KEY=${DEEPSEEK_API_KEY}
    ports:
      - "8121:8121"
    volumes:
      - ./logs:/app/logs
    networks:
      - app-network
    depends_on:
      - nginx
    healthcheck:
      test: ["CMD", "node", "-e", "const http = require('http'); const options = { host: 'localhost', port: 8121, path: '/models', timeout: 2000 }; const req = http.request(options, (res) => { process.exit(res.statusCode === 200 || res.statusCode === 500 ? 0 : 1) }); req.on('error', () => process.exit(1)); req.end();"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Nginx 反向代理
  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./ssl:/etc/nginx/ssl
      - ./logs/nginx:/var/log/nginx
    networks:
      - app-network
    depends_on:
      - chat-sse-be

  # 前端服务 (可选，如果有前端)
  frontend:
    image: nginx:alpine
    container_name: frontend-app
    restart: unless-stopped
    ports:
      - "3000:80"
    volumes:
      - ./frontend/dist:/usr/share/nginx/html
      - ./nginx/frontend.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  logs:
    driver: local 